@host=https://localhost:7188/api

POST {{host}}/products
Content-Type: application/json

{
    "name": "Samsung Galaxy Fold 4",
    "description": "A Samsung's smartphone",
    "brandId": "64040072-B9E7-495A-938B-7ED60BB3D378",
    "categoryId": "09523ab4-d845-4f36-823e-51edf6911f53"
}