@host=https://localhost:7188/api

POST {{host}}/products
Content-Type: application/json

{
    "name": "Testing 2",
    "description": "demo",
    "brandId": "FFE97F58-9DE5-4D89-A873-E9F71443FB59",
    "categoryId": "a9103709-d7ef-4d76-9af8-1904e2d33882",
    "images": [
        {
            "imageUrl": "test",
            "displayOrder": "1"
        }
    ]
}