version: '3.9'
services:
  db:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '1433:1433'

    environment:
      SA_PASSWORD: 'Password123'
      ACCEPT_EULA: Y

  be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - db
      